fmod BUBBLE is 
    inc QID-LIST .
    pr COMMAND-SIGN .

    op token : Qid -> @Token@
    [special (id-hook Bubble   (1 1)
           op-hook qidSymbol (<Qids> : ~> Qid))] .

    op bubble : QidList -> @String@ 
     [special 
       (id-hook Bubble     (1 -1) 
        op-hook qidListSymbol (__ : QidList QidList ~> QidList) 
        op-hook qidSymbol  (<Qids> : ~> Qid) 
        id-hook Exclude    (string{))] . 

endfm